# Generated by Django 5.0.7 on 2025-02-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('company_title', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('pay_period', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_views', models.IntegerField(blank=True, null=True)),
                ('med_salary', models.IntegerField(blank=True, null=True)),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('formatted_applies', models.CharField(blank=True, max_length=100, null=True)),
                ('original_list', models.BigIntegerField(blank=True, null=True)),
                ('remote_all', models.FloatField(blank=True, null=True)),
                ('job_postin', models.URLField(blank=True, max_length=50, null=True)),
                ('application', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.BigIntegerField(blank=True, null=True)),
                ('closed_tim', models.BigIntegerField(blank=True, null=True)),
                ('formatted_skills_desc', models.TextField(blank=True, null=True)),
                ('listed_time', models.BigIntegerField(blank=True, null=True)),
                ('posting_dc', models.BigIntegerField(blank=True, null=True)),
                ('sponsored', models.IntegerField(blank=True, null=True)),
                ('work_type', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('compensation', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized', models.IntegerField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
