# Generated by Django 5.0.7 on 2025-02-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='formatted_applies',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_postin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
