# Generated by Django 5.0.2 on 2025-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0003_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
