# Generated by Django 5.0.2 on 2025-02-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0004_job_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(unique=True)),
                ('medoid_vector', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='is_medoid',
            field=models.BooleanField(default=False),
        ),
    ]
