# Generated by Django 5.0.2 on 2025-02-12 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1', '0005_cluster_job_is_medoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='medoid_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medoid_for_cluster', to='backend1.job'),
        ),
    ]
